## Preliminaries

### Study question 1.4.1

In [1]:
import networkx as nx

g = nx.DiGraph()

nodes = ['W', 'X', 'Y', 'Z', 'T']
edges = [('X', 'W'), ('X', 'Y'), ('W', 'Y'), ('W', 'Z'), ('Y', 'Z'), ('Y', 'T'), ('Z', 'T')]

_ = [g.add_node(n) for n in nodes]
_ = [g.add_edge(p, c) for p, c in edges]

In [2]:
list(g.predecessors('Z'))

['W', 'Y']

In [3]:
from networkx.algorithms.dag import ancestors

list(ancestors(g, 'Z'))

['Y', 'W', 'X']

In [4]:
list(g.successors('W'))

['Y', 'Z']

In [5]:
from networkx.algorithms.dag import descendants

list(descendants(g, 'W'))

['Y', 'Z', 'T']

In [6]:
from networkx.algorithms.simple_paths import all_simple_paths

list(all_simple_paths(g, 'X', 'T'))

[['X', 'W', 'Y', 'Z', 'T'],
 ['X', 'W', 'Y', 'T'],
 ['X', 'W', 'Z', 'T'],
 ['X', 'Y', 'Z', 'T'],
 ['X', 'Y', 'T']]

### Study question 1.5.1

In [7]:
import numpy as np
import pandas as pd

np.random.seed(37)

N = 10_000

U_x = np.random.normal(0, 1, N)
U_y = np.random.normal(0, 1, N)
U_z = np.random.normal(0, 1, N)

X = U_x
Y = (1/3) * X + U_y
Z = (1/16) * Y + U_z

df = pd.DataFrame({
    'X': X,
    'Y': Y,
    'Z': Z
})

In [8]:
df.head()

X         Y         Z
0 -0.054464  0.115728  0.229677
1  0.674308 -0.736683  0.766547
2  0.346647  0.011832  0.599696
3 -1.300346 -0.579125 -1.107032
4  1.518512 -0.544518 -0.403825

In [9]:
from sklearn.linear_model import LinearRegression

X = df[['Y']]
y = df.Z

model = LinearRegression().fit(X, y)
model.predict(np.array([[3]]))

array([0.21822383])

In [10]:
X = df[['X']]
y = df.Z

model = LinearRegression().fit(X, y)
model.predict(np.array([[3]]))

array([0.09937442])

In [11]:
X = df[['X', 'Y']]
y = df.Z

model = LinearRegression().fit(X, y)
model.predict(np.array([[1, 3]]))

array([0.21900358])

In [12]:
df.cov()

X         Y         Z
X  0.990700  0.338077  0.031365
Y  0.338077  1.125325  0.079959
Z  0.031365  0.079959  0.990133

## Graphical Models and Their Applications

### Study question 2.3.1

In [13]:
fig2_5 = nx.DiGraph()

nodes = ['X', 'R', 'S', 'T', 'U', 'V', 'Y']
edges = [('X', 'R'), ('R', 'S'), ('S', 'T'), ('U', 'T'), ('V', 'U'), ('V', 'Y')]

_ = [fig2_5.add_node(n) for n in nodes]
_ = [fig2_5.add_edge(p, c) for p, c in edges]

In [14]:
fig2_6 = nx.DiGraph()

nodes = ['X', 'R', 'S', 'T', 'U', 'V', 'Y', 'P']
edges = [('X', 'R'), ('R', 'S'), ('S', 'T'), ('U', 'T'), ('V', 'U'), ('V', 'Y'), ('T', 'P')]

_ = [fig2_6.add_node(n) for n in nodes]
_ = [fig2_6.add_edge(p, c) for p, c in edges]