# QED sampling

In [11]:
import numpy as np
import pandas as pd

np.random.seed(37)
np.set_printoptions(
    precision=10,
    formatter={'float': lambda v: f'{v:.10f}'}
)

n = 10_000
A = np.random.normal(0, 1, n)
B = np.random.normal(0, 1, n)
C = np.random.normal(A, 1, n)
D = np.random.normal(0.2 * A + 0.8 * B, 1, n)

In [12]:
E = np.vstack([A, B, C, D]).T
E.shape

(10000, 4)

In [17]:
np.cov(E.T)

array([[0.9907002440, 0.0078436913, 1.0009352395, 0.2036429872],
       [0.0078436913, 1.0100180410, 0.0140579594, 0.7985879082],
       [1.0009352395, 0.0140579594, 1.9957039315, 0.2253232977],
       [0.2036429872, 0.7985879082, 0.2253232977, 1.6851371822]])

In [21]:
pd.DataFrame(E).cov()

0         1         2         3
0  0.990700  0.007844  1.000935  0.203643
1  0.007844  1.010018  0.014058  0.798588
2  1.000935  0.014058  1.995704  0.225323
3  0.203643  0.798588  0.225323  1.685137

In [24]:
pd.DataFrame(E).mean().values

array([0.0017234068, -0.0091710062, 0.0067119637, -0.0180855967])

In [25]:
pd.DataFrame(E).var().values

array([0.9907002440, 1.0100180410, 1.9957039315, 1.6851371822])