In [3]:
import numpy as np

P = np.array([[0.9, 0.1], [0.5, 0.5]])
s = np.array([1.0, 0.0])

In [4]:
s.dot(P)

array([0.9, 0.1])

In [5]:
s.dot(P).dot(P)

array([0.86, 0.14])

In [8]:
P_curr = s.dot(P)

for it in range(100):
    P_next = P_curr.dot(P)
    
P_next

array([0.86, 0.14])