# Nearest Neighbors

## Ball tree

In [1]:
import numpy as np
from sklearn.neighbors import BallTree

X = np.array([
    [-2, -2],
    [-1, -1],
    [0, 0],
    [1, 1],
    [2, 2]])

q = np.array([
    [0, 0],
    [-1.5, -1.5]
])

tree = BallTree(X)
distance, indices = tree.query(q, k=2)

print('distances')
print(distance)
print('-')
print('indices')
print(indices)

distances
[[0.         1.41421356]
 [0.70710678 0.70710678]]
-
indices
[[2 1]
 [1 0]]


## KD tree

In [2]:
from sklearn.neighbors import KDTree


X = np.array([
    [-2, -2],
    [-1, -1],
    [0, 0],
    [1, 1],
    [2, 2]])

q = np.array([
    [0, 0],
    [-1.5, -1.5]
])

tree = KDTree(X)
distance, indices = tree.query(q, k=2)

print('distances')
print(distance)
print('-')
print('indices')
print(indices)

distances
[[0.         1.41421356]
 [0.70710678 0.70710678]]
-
indices
[[2 1]
 [1 0]]


## Nearest centroid

In [3]:
from sklearn.neighbors import NearestCentroid

X = np.array([
    [-2, -2],
    [-1, -1],
    [1, 1],
    [2, 2]])

y = np.array([0, 0, 1, 1])

q = np.array([
    [1.5, 1.5],
    [-1.5, -1.5]
])

nc = NearestCentroid()
nc.fit(X, y)

nc.predict(q)

array([1, 0])

## Nearest neighbor

In [4]:
from sklearn.neighbors import NearestNeighbors

X = np.array([
    [-2, -2],
    [-1, -1],
    [0, 0],
    [1, 1],
    [2, 2]])

q = np.array([
    [0, 0],
    [-1.5, -1.5]
])

nn = NearestNeighbors(n_neighbors=2)
nn.fit(X)
distance, indices = nn.kneighbors(q)

print('distances')
print(distance)
print('-')
print('indices')
print(indices)

distances
[[0.         1.41421356]
 [0.70710678 0.70710678]]
-
indices
[[2 1]
 [0 1]]
