# Data preprocessing

## Binarizer

In [1]:
from sklearn.preprocessing import Binarizer

X = [[1.0],
     [-1.0],
     [1.0],
     [-1.0]]

t = Binarizer()
t.fit(X)
t.transform(X)

array([[1.],
       [0.],
       [1.],
       [0.]])

## K-bins discretizer

In [2]:
from sklearn.preprocessing import KBinsDiscretizer

X = [[-2.0, 2.0],
     [-1.0, 1.0],
     [0.0, 0.0],
     [1.0, -1.0], 
     [2.0, -2.0]]

t = KBinsDiscretizer(n_bins=3, encode='ordinal', strategy='uniform')
t.fit(X)
t.transform(X)

array([[0., 2.],
       [0., 2.],
       [1., 1.],
       [2., 0.],
       [2., 0.]])

## Label binarizer

In [3]:
import numpy as np
from sklearn.preprocessing import LabelBinarizer

t = LabelBinarizer()
t.fit([0, 1, 2])

LabelBinarizer(neg_label=0, pos_label=1, sparse_output=False)

In [4]:
t.transform([0, 0, 2, 2, 1, 1])

array([[1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0]])

In [5]:
t.inverse_transform(np.array([[1, 0, 0]]))

array([0])

In [6]:
t.inverse_transform(np.array([[0, 0, 1]]))

array([2])

In [7]:
t.inverse_transform(np.array([[0, 1, 0]]))

array([1])

## Label encoder

In [8]:
from sklearn.preprocessing import LabelEncoder

t = LabelEncoder()
t.fit([99, 100, 200])

LabelEncoder()

In [9]:
t.transform([99, 99, 100, 200, 100, 200])

array([0, 0, 1, 2, 1, 2])

In [10]:
t.inverse_transform([0, 0, 2, 2, 1, 1])

array([ 99,  99, 200, 200, 100, 100])