# Data preprocessing

In [12]:
from sklearn.preprocessing import Binarizer

X = [[1.0],
     [-1.0],
     [1.0],
     [-1.0]]

t = Binarizer()
t.fit(X)
t.transform(X)

array([[1.],
       [0.],
       [1.],
       [0.]])

In [19]:
from sklearn.preprocessing import KBinsDiscretizer

X = [[-2.0, 2.0],
     [-1.0, 1.0],
     [0.0, 0.0],
     [1.0, -1.0], 
     [2.0, -2.0]]

t = KBinsDiscretizer(n_bins=3, encode='ordinal', strategy='uniform')
t.fit(X)
t.transform(X)

array([[0., 2.],
       [0., 2.],
       [1., 1.],
       [2., 0.],
       [2., 0.]])

In [34]:
import numpy as np
from sklearn.preprocessing import LabelBinarizer

t = LabelBinarizer()
t.fit([0, 1, 2])

# transform labels
print(t.transform([0, 0, 2, 2, 1, 1]))

# inverse transform
print(t.inverse_transform(np.array([[1, 0, 0]])))
print(t.inverse_transform(np.array([[0, 0, 1]])))
print(t.inverse_transform(np.array([[0, 1, 0]])))

[[1 0 0]
 [1 0 0]
 [0 0 1]
 [0 0 1]
 [0 1 0]
 [0 1 0]]
[0]
[2]
[1]


In [39]:
from sklearn.preprocessing import LabelEncoder

t = LabelEncoder()
t.fit([99, 100, 200])

print(t.transform([99, 99, 100, 200, 100, 200]))

print(t.inverse_transform([0, 0, 2, 2, 1, 1]))

[0 0 1 2 1 2]
[ 99  99 200 200 100 100]
