# Guassian DAGs

## Converging

In [1]:
import numpy as np
import pandas as pd
from scipy.stats import zscore


np.random.seed(37)

n = 1_000
x1 = np.random.normal(1, 1, n) 
x3 = np.random.normal(2, 1, n) 
x2 = 1 + (2 * x1) - (1 * x3) + np.random.normal(0, 0.1, n)

X = pd.DataFrame({
    'x1': x1,
    'x2': x2,
    'x3': x3
})

# X = X.apply(zscore)

X

x1        x2        x3
0    0.945536  1.556479  1.340046
1    1.674308  2.309109  1.927612
2    1.346647  2.659741  1.011724
3   -0.300346 -2.305890  2.510436
4    2.518512  3.651125  2.442500
..        ...       ...       ...
995  0.401151  0.058276  1.776478
996  0.748119  1.364580  1.005029
997  1.371860  1.364518  2.333035
998  2.022343  4.032086  0.975413
999  1.429555  1.587260  2.245331

[1000 rows x 3 columns]

In [2]:
M, S = X.mean().values, X.cov().values

In [3]:
M

array([1.01277839, 1.04063165, 1.9839153 ])

In [4]:
S

array([[ 9.63461496e-01,  1.92950806e+00, -3.71353761e-03],
       [ 1.92950806e+00,  4.86316962e+00, -9.91394474e-01],
       [-3.71353761e-03, -9.91394474e-01,  9.78656526e-01]])

In [5]:
def conditional(M, S, obs):
    a = np.array([v for _, v in obs.items()])
    
    i_1 = [i for i in range(M.shape[0]) if i not in obs]
    i_2 = [i for i in range(M.shape[0]) if i in obs]
    
    m_1, m_2 = M[i_1], M[i_2]
    
    S_11 = S[i_1][:,i_1]
    S_12 = S[i_1][:,i_2]
    S_21 = S[i_2][:,i_1]
    S_22 = np.linalg.inv(S[i_2][:,i_2])
     
    _r = S_12.dot(S_22)
    _m = m_1 + _r.dot(a - m_2)
    _s = S_11 - _r.dot(S_21)
    
    return _m, _s

In [6]:
_m, _s = conditional(M, S, {0: 2, 1: 1})

In [7]:
_m

array([3.96749869])

In [8]:
_s

array([[0.00947795]])