# Guassian DAGs

## Diverging

In [2]:
import numpy as np
import pandas as pd
from scipy.stats import zscore


np.random.seed(37)

n = 1_000
x2 = np.random.normal(1, 1, n)
x1 = 4 + 2 * x2 + np.random.normal(0, 0.1, n)
x3 = 1 - 3 * x2 + np.random.normal(0, 0.1, n)

X = pd.DataFrame({
    'x1': x1,
    'x2': x2,
    'x3': x3
})

# X = X.apply(zscore)

X

x1        x2        x3
0    5.825077  0.945536 -1.831157
1    7.341377  1.674308 -4.134819
2    6.594466  1.346647 -3.061770
3    3.450351 -0.300346  1.706277
4    9.081274  2.518512 -6.498935
..        ...       ...       ...
995  4.779951  0.401151 -0.171004
996  5.396740  0.748119 -1.370984
997  6.777024  1.371860 -3.161750
998  7.942227  2.022343 -5.104215
999  6.883643  1.429555 -3.315183

[1000 rows x 3 columns]

In [3]:
M, S = X.mean().values, X.cov().values

In [4]:
M

array([ 6.0239483 ,  1.01277839, -2.03934499])

In [5]:
S

array([[ 3.86214714,  1.92655164, -5.78244293],
       [ 1.92655164,  0.9634615 , -2.89151295],
       [-5.78244293, -2.89151295,  8.68762933]])

In [6]:
def conditional(M, S, obs):
    a = np.array([v for _, v in obs.items()])
    
    i_1 = [i for i in range(M.shape[0]) if i not in obs]
    i_2 = [i for i in range(M.shape[0]) if i in obs]
    
    m_1, m_2 = M[i_1], M[i_2]
    
    S_11 = S[i_1][:,i_1]
    S_12 = S[i_1][:,i_2]
    S_21 = S[i_2][:,i_1]
    S_22 = np.linalg.inv(S[i_2][:,i_2])
     
    _r = S_12.dot(S_22)
    _m = m_1 + _r.dot(a - m_2)
    _s = S_11 - _r.dot(S_21)
    
    return _m, _s

In [46]:
_m, _s = conditional(M, S, {1: 1})

In [47]:
_m

array([ 5.99839645, -2.00099486])

In [48]:
_s

array([[ 0.00978642, -0.00053152],
       [-0.00053152,  0.00970375]])