# Markov Chain, Stationary Distribution

In [1]:
import numpy as np

M = np.array([
    [0, 1, 1, 1, 1],
    [0, 0, 0, 0, 0],
    [0, 1, 0, 0, 1],
    [0, 1, 1, 0, 1],
    [0, 1, 0, 0, 0]
])
M

array([[0, 1, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [0, 1, 0, 0, 1],
       [0, 1, 1, 0, 1],
       [0, 1, 0, 0, 0]])

In [2]:
for r, s in enumerate(M.sum(axis=1)):
    if s == 0:
        M[r, :] = 1

In [3]:
M

array([[0, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 1, 0, 0, 1],
       [0, 1, 1, 0, 1],
       [0, 1, 0, 0, 0]])

In [4]:
M = np.array([M[r,:] * s for r, s in enumerate(1 / M.sum(axis=1))])

In [5]:
M

array([[0.        , 0.25      , 0.25      , 0.25      , 0.25      ],
       [0.2       , 0.2       , 0.2       , 0.2       , 0.2       ],
       [0.        , 0.5       , 0.        , 0.        , 0.5       ],
       [0.        , 0.33333333, 0.33333333, 0.        , 0.33333333],
       [0.        , 1.        , 0.        , 0.        , 0.        ]])

## Power Method

Uses [power iteration](https://en.wikipedia.org/wiki/Power_iteration).

In [6]:
X = M.dot(M)
for _ in range(10):
    Y = X.dot(X)
    
    x = np.diag(X)
    y = np.diag(Y)
    d = np.linalg.norm(x - y, 1)
    
    if d < 0.001:
        break
    
    X = Y
    
np.diag(X)

array([0.08759149, 0.43795601, 0.1459856 , 0.10948932, 0.2189781 ])

## Scikit-Learn

In [46]:
from sklearn.decomposition import TruncatedSVD

svd = TruncatedSVD(n_components=1, n_iter=100, random_state=37)
svd.fit(M)

TruncatedSVD(n_components=1, n_iter=100, random_state=37)

In [47]:
svd.singular_values_

array([1.30917263])

In [48]:
svd.explained_variance_

array([0.04276521])

In [49]:
svd.explained_variance_ratio_

array([0.28895415])

In [50]:
svd.components_

array([[0.03729224, 0.90159379, 0.18926652, 0.09420146, 0.37555584]])

In [51]:
from scipy.special import softmax

softmax(svd.components_)

array([[0.14288678, 0.33912004, 0.16633883, 0.15125419, 0.20040016]])

## Numpy

In [7]:
w, v = np.linalg.eig(M)

In [8]:
w

array([ 1.        +0.j        , -0.19142147+0.37381746j,
       -0.19142147-0.37381746j, -0.20857853+0.06116392j,
       -0.20857853-0.06116392j])

In [9]:
v

array([[-0.4472136 +0.j        , -0.13318281-0.29145268j,
        -0.13318281+0.29145268j,  0.09480498+0.27007682j,
         0.09480498-0.27007682j],
       [-0.4472136 +0.j        , -0.20117745-0.11344862j,
        -0.20117745+0.11344862j,  0.06206367-0.04694846j,
         0.06206367+0.04694846j],
       [-0.4472136 +0.j        ,  0.58322907+0.j        ,
         0.58322907-0.j        ,  0.65373336+0.j        ,
         0.65373336-0.j        ],
       [-0.4472136 +0.j        ,  0.17783267-0.41202544j,
         0.17783267+0.41202544j, -0.52619684-0.28210412j,
        -0.52619684+0.28210412j],
       [-0.4472136 +0.j        , -0.02210768+0.54949103j,
        -0.02210768-0.54949103j, -0.33477316+0.12691826j,
        -0.33477316-0.12691826j]])

## Scipy

In [13]:
from scipy.linalg import eigh

w, v = eigh(M)

In [14]:
w

array([-1.05505960e+00, -3.28934060e-01,  2.22044605e-16,  2.49512669e-01,
        1.33448099e+00])

In [15]:
v

array([[-1.29549822e-01,  2.25187815e-02,  9.80580676e-01,
         9.78051832e-02,  1.07728514e-01],
       [ 6.83413913e-01, -3.70359711e-02,  3.51927057e-16,
         1.22018162e-01,  7.18808270e-01],
       [-2.84007052e-01, -6.78253442e-01, -5.42983743e-16,
        -5.89098017e-01,  3.35075796e-01],
       [-1.26187773e-01,  7.24855932e-01, -5.63414323e-16,
        -6.23989498e-01,  2.63244431e-01],
       [-6.47749109e-01,  1.12593907e-01, -1.96116135e-01,
         4.89025916e-01,  5.38642571e-01]])