# Markov Chain, Stationary Distribution

In [1]:
import numpy as np

M = np.array([
    [0, 1, 1, 1, 1],
    [0, 0, 0, 0, 0],
    [0, 1, 0, 0, 1],
    [0, 1, 1, 0, 1],
    [0, 1, 0, 0, 0]
])
M

array([[0, 1, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [0, 1, 0, 0, 1],
       [0, 1, 1, 0, 1],
       [0, 1, 0, 0, 0]])

In [2]:
for r, s in enumerate(M.sum(axis=1)):
    if s == 0:
        M[r, :] = 1

In [3]:
M

array([[0, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 1, 0, 0, 1],
       [0, 1, 1, 0, 1],
       [0, 1, 0, 0, 0]])

In [4]:
M = np.array([M[r,:] * s for r, s in enumerate(1 / M.sum(axis=1))])

In [5]:
M

array([[0.        , 0.25      , 0.25      , 0.25      , 0.25      ],
       [0.2       , 0.2       , 0.2       , 0.2       , 0.2       ],
       [0.        , 0.5       , 0.        , 0.        , 0.5       ],
       [0.        , 0.33333333, 0.33333333, 0.        , 0.33333333],
       [0.        , 1.        , 0.        , 0.        , 0.        ]])

## Power Method

Uses [power iteration](https://en.wikipedia.org/wiki/Power_iteration).

In [6]:
X = M.dot(M)
for _ in range(10):
    Y = X.dot(X)
    
    x = np.diag(X)
    y = np.diag(Y)
    d = np.linalg.norm(x - y, 1)
    
    if d < 0.001:
        break
    
    X = Y
    
np.diag(X)

array([0.08759149, 0.43795601, 0.1459856 , 0.10948932, 0.2189781 ])

## Numpy, eig

In [26]:
S, U = np.linalg.eig(M.T)

In [29]:
S.real

array([ 1.        , -0.19142147, -0.19142147, -0.20857853, -0.20857853])

In [30]:
U.real

array([[-0.16531686, -0.16178269, -0.16178269, -0.6152745 , -0.6152745 ],
       [-0.8265843 ,  0.7453579 ,  0.7453579 ,  0.6968425 ,  0.6968425 ],
       [-0.2755281 , -0.2841635 , -0.2841635 ,  0.09145666,  0.09145666],
       [-0.20664607, -0.28528506, -0.28528506,  0.0053999 ,  0.0053999 ],
       [-0.41329215, -0.01412664, -0.01412664, -0.17842455, -0.17842455]])

In [31]:
(U[:,np.isclose(S, 1)][:,0] / U[:,np.isclose(S, 1)][:,0].sum()).real

array([0.08759124, 0.4379562 , 0.1459854 , 0.10948905, 0.2189781 ])

## Scipy, eig

In [32]:
from scipy.linalg import eig

S, U = eig(M.T)

In [33]:
S.real

array([ 1.        , -0.19142147, -0.19142147, -0.20857853, -0.20857853])

In [34]:
U.real

array([[-0.16531686, -0.16178269, -0.16178269, -0.6152745 , -0.6152745 ],
       [-0.8265843 ,  0.7453579 ,  0.7453579 ,  0.6968425 ,  0.6968425 ],
       [-0.2755281 , -0.2841635 , -0.2841635 ,  0.09145666,  0.09145666],
       [-0.20664607, -0.28528506, -0.28528506,  0.0053999 ,  0.0053999 ],
       [-0.41329215, -0.01412664, -0.01412664, -0.17842455, -0.17842455]])

In [14]:
(U[:,np.isclose(S, 1)][:,0] / U[:,np.isclose(S, 1)][:,0].sum()).real

array([0.08759124, 0.4379562 , 0.1459854 , 0.10948905, 0.2189781 ])

In [62]:
U, S, V = np.linalg.svd(M)

In [63]:
U

array([[-0.29801601,  0.42513093, -0.37178244, -0.08009176, -0.7653844 ],
       [-0.24410988,  0.37941413, -0.44963453, -0.51052396,  0.57762389],
       [-0.48776976,  0.20162381,  0.7756217 , -0.343992  , -0.0388457 ],
       [-0.37336969,  0.40956329,  0.02016766,  0.78321156,  0.28111547],
       [-0.68867449, -0.68331132, -0.24002262,  0.03463756,  0.00156949]])

In [64]:
S

array([1.30917263, 0.62135328, 0.34374807, 0.21387074, 0.13934507])

In [65]:
np.square(S)

array([1.71393296, 0.38607989, 0.11816273, 0.04574069, 0.01941705])

In [66]:
V

array([[-3.72922368e-02, -9.01593795e-01, -1.89266517e-01,
        -9.42014643e-02, -3.75555838e-01],
       [ 1.22125093e-01, -4.24577728e-01,  5.12891245e-01,
         2.93175502e-01,  6.75136957e-01],
       [-2.61607014e-01, -8.25073102e-02, -5.12439134e-01,
        -5.31995764e-01,  6.15744228e-01],
       [-4.77413559e-01,  7.40796013e-03,  6.49657758e-01,
        -5.71035244e-01, -1.54547608e-01],
       [ 8.29055375e-01,  2.18700290e-04,  1.28342076e-01,
        -5.44126333e-01, -1.10446126e-02]])

In [67]:
U[:,0] / U[:,0].sum()

array([0.14245917, 0.11669068, 0.23316625, 0.17848013, 0.32920378])

In [68]:
U[0,:] / U[0,:].sum()

array([ 0.27337315, -0.38997697,  0.34103985,  0.07346899,  0.70209497])

In [53]:
eigen_vals, eigen_vecs = np.linalg.eig(M)
U, Sigma, Vh = np.linalg.svd(X, full_matrices=False, compute_uv=True)

In [55]:
eigen_vals.real

array([ 1.        , -0.19142147, -0.19142147, -0.20857853, -0.20857853])

In [60]:
np.square(Sigma.real) / (M.shape[0] - 1)

array([3.50911009e-01, 5.36169199e-13, 1.73525640e-13, 6.94761130e-22,
       1.25951744e-23])