# Learning

## Training and testing

In [9]:
from torchvision import datasets, models, transforms
import torch.optim as optim
import torch.nn as nn
from torchvision.transforms import *
from torch.utils.data import DataLoader
import torch
import numpy as np
from collections import defaultdict
import time
import copy

def train(dataloaders, model, criterion, optimizer, scheduler, device, num_epochs=20):
    def format_start_stop(start, stop):
        elapsed = stop - start
        return f'{elapsed//60:.0f}m {elapsed%50:.0f}s'
    
    best_model_weights = copy.deepcopy(model.state_dict())
    best_acc = -1.0
    
    loop_start = time.time()
    
    for epoch in range(num_epochs):
        train_loss, train_acc = 0.0, 0.0
        test_loss, test_acc = 0.0, 0.0
        train_start, test_start = 0.0, 0.0
        train_stop, test_stop = 0.0, 0.0
        
        for phase in ['train', 'test']:
            if phase == 'train':
                optimizer.step()
                scheduler.step()
                model.train()
                train_start = time.time()
            else:
                model.eval()
                test_start = time.time()

            running_loss = 0.0
            running_corrects = 0

            n = 0
            dataloader = dataloaders[phase]
            for inputs, labels in dataloader:
                inputs = inputs.to(device)
                labels = labels.to(device)

                optimizer.zero_grad()

                with torch.set_grad_enabled(phase == 'train'):
                    outputs = model(inputs)
                    loss = criterion(outputs, labels)
                    _, preds = torch.max(outputs, 1)
                    
                    if phase == 'train':
                        loss.backward()
                        optimizer.step()
                running_loss += loss.mean() * inputs.size(0)
                running_corrects += torch.sum(preds == labels.data)
                n += len(labels)

            epoch_loss = running_loss / float(n)
            epoch_acc = running_corrects.double() / float(n)
            
            if phase == 'train':
                train_stop = time.time()
                train_loss, train_acc = epoch_loss, epoch_acc
            else:
                test_stop = time.time()
                test_loss, test_acc = epoch_loss, epoch_acc
                
                if epoch_acc > best_acc:
                    best_model_weights = copy.deepcopy(model.state_dict())
                    best_acc = epoch_acc                
        
        train_time = format_start_stop(train_start, train_stop)
        test_time = format_start_stop(test_start, test_stop)
        
        train_metrics = f'TRAIN: {train_loss:.4f}, {train_acc:.4f}, {train_time}'
        test_metrics = f'TEST: {test_loss:.4f}, {test_acc:.4f}, {test_time}'
        print(f'epoch {str(epoch + 1).zfill(2)}/{str(num_epochs).zfill(2)} | {train_metrics} | {test_metrics}')
    
    loop_stop = time.time()
    loop_time = format_start_stop(loop_start, loop_stop)
    print(f'completed learning in {loop_time}, best accuracy {best_acc:.4f}')
    
    model.load_state_dict(best_model_weights)
    return model

def get_dataloaders():
    def clean_up(path):
        import os
        from shutil import rmtree
        
        ipynb_checkpoints = f'{path}/.ipynb_checkpoints'
        if os.path.exists(ipynb_checkpoints):
            rmtree(ipynb_checkpoints)
            
    def get_dataloader(phase):
        path = f'./shapes/{phase}'
        clean_up(path)
        
        transform = transforms.Compose([Resize(224), ToTensor()])
        image_folder = datasets.ImageFolder(path, transform=transform)
        # print(path, image_folder.classes)
        return DataLoader(image_folder, batch_size=4, shuffle=True, num_workers=4)
    
    return {phase: get_dataloader(phase) for phase in ['train', 'test', 'valid']}

np.random.seed(37)
torch.manual_seed(37)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
pretrained=True
num_classes = 3
num_epochs = 5

dataloaders = get_dataloaders()

model = models.resnet18(pretrained=pretrained)
model.fc = nn.Linear(model.fc.in_features, num_classes)
model = model.to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Rprop(model.parameters(), lr=0.01)
scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=1)

model = train(dataloaders, model, criterion, optimizer, scheduler, device, num_epochs=num_epochs)

epoch 01/05 | TRAIN: 1.1829, 0.6667, 0m 1s | TEST: 2.1690, 0.4000, 0m 0s
epoch 02/05 | TRAIN: 0.8402, 0.8000, 0m 1s | TEST: 0.0073, 1.0000, 0m 0s
epoch 03/05 | TRAIN: 0.7039, 0.8667, 0m 1s | TEST: 0.0217, 1.0000, 0m 0s
epoch 04/05 | TRAIN: 0.2520, 0.8667, 0m 1s | TEST: 0.0139, 1.0000, 0m 0s
epoch 05/05 | TRAIN: 0.4865, 0.8667, 0m 1s | TEST: 0.0039, 1.0000, 0m 0s
completed learning in 0m 5s, best accuracy 1.0000


## Validation

In [22]:
import torch.nn.functional as F

def validate(model, dataloader):
    results = []
    truths = []
    for inputs, labels in dataloader:
        inputs = inputs.to(device)
        labels = labels.to(device)

        optimizer.zero_grad()

        with torch.set_grad_enabled(False):
            outputs = model(inputs)
            _, preds = torch.max(outputs, 1)
            probs = F.softmax(outputs, dim=1).cpu().detach().numpy()
            
            truths.append(labels.cpu().detach().numpy())
            results.append(probs)
    return np.vstack(results), np.hstack(truths)
            
P, y = validate(model, dataloaders['valid'])

In [23]:
P

array([[1.09239802e-04, 9.98647034e-01, 1.24368677e-03],
       [9.99996543e-01, 4.27103942e-07, 3.02703666e-06],
       [8.24902789e-04, 9.94648993e-01, 4.52606427e-03],
       [3.14544668e-05, 9.99468505e-01, 5.00007591e-04],
       [1.00000000e+00, 1.89986444e-08, 3.60023762e-08],
       [6.85336943e-08, 3.33887947e-05, 9.99966502e-01],
       [2.31350423e-05, 9.99559224e-01, 4.17684234e-04],
       [9.99996662e-01, 2.38815005e-06, 9.01562430e-07],
       [7.80323899e-06, 1.05366234e-04, 9.99886870e-01],
       [6.09260278e-05, 9.24190972e-04, 9.99014854e-01],
       [7.34221772e-04, 9.94967997e-01, 4.29777801e-03],
       [9.99832392e-01, 1.10261331e-04, 5.72778845e-05],
       [5.12135259e-08, 3.99566670e-06, 9.99995947e-01],
       [9.99997616e-01, 6.17816795e-07, 1.76223170e-06],
       [3.50799993e-08, 5.10070663e-07, 9.99999523e-01]], dtype=float32)

In [24]:
y

array([1, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2, 0, 2])

In [59]:
from sklearn.metrics import roc_curve, auc

fpr = dict()
tpr = dict()
roc_auc = dict()

for i in range(num_classes):
    fpr[i], tpr[i], _ = roc_curve([1 if label == i else 0 for label in y], P[:, i])
    roc_auc[i] = auc(fpr[i], tpr[i])
    
y_test = np.array([[1 if label == i else 0 for label in y] for i in range(num_classes)]).ravel()
y_preds = P.ravel()
fpr['micro'], tpr['micro'], _ = roc_curve(y_test, y_preds)
roc_auc['micro'] = auc(fpr['micro'], tpr['micro'])

In [60]:
all_fpr = np.unique(np.concatenate([fpr[i] for i in range(num_classes)]))

In [61]:
from scipy import interp

mean_tpr = np.zeros_like(all_fpr)
for i in range(num_classes):
    mean_tpr += interp(all_fpr, fpr[i], tpr[i])
mean_tpr /= num_classes

fpr['macro'], tpr['macro'] = all_fpr, mean_tpr
roc_auc['macro'] = auc(fpr['macro'], tpr['macro'])

In [62]:
roc_auc

{0: 1.0, 1: 1.0, 2: 1.0, 'micro': 0.54, 'macro': 1.0}

In [63]:
y_test

array([0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       1])

In [64]:
y_preds

array([1.09239802e-04, 9.98647034e-01, 1.24368677e-03, 9.99996543e-01,
       4.27103942e-07, 3.02703666e-06, 8.24902789e-04, 9.94648993e-01,
       4.52606427e-03, 3.14544668e-05, 9.99468505e-01, 5.00007591e-04,
       1.00000000e+00, 1.89986444e-08, 3.60023762e-08, 6.85336943e-08,
       3.33887947e-05, 9.99966502e-01, 2.31350423e-05, 9.99559224e-01,
       4.17684234e-04, 9.99996662e-01, 2.38815005e-06, 9.01562430e-07,
       7.80323899e-06, 1.05366234e-04, 9.99886870e-01, 6.09260278e-05,
       9.24190972e-04, 9.99014854e-01, 7.34221772e-04, 9.94967997e-01,
       4.29777801e-03, 9.99832392e-01, 1.10261331e-04, 5.72778845e-05,
       5.12135259e-08, 3.99566670e-06, 9.99995947e-01, 9.99997616e-01,
       6.17816795e-07, 1.76223170e-06, 3.50799993e-08, 5.10070663e-07,
       9.99999523e-01], dtype=float32)

In [65]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test, y_preds)

0.54