# Tensor

## Creation

In [45]:
import torch
import numpy as np

# one element
a = torch.tensor([1])

# two element
b = torch.tensor([1, 2])

# two float elements
c = torch.tensor([1., 2.])

# matrix 
d = torch.tensor([[1., 2.], [3., 4.]])

# from python array
e = torch.as_tensor([1., 2., 3.], dtype=torch.float32)

# from numpy array
f = torch.from_numpy(np.array([1.0, 2.0]))

# make tensor of zeros
g = torch.zeros(1)
h = torch.zeros(1, 2)
i = torch.zeros(2, 2)

# empty tensor
j = torch.empty(2, 2)

# make tensor ones
k = torch.ones(2, 2)

# make tensor from range
l = torch.arange(start=0, end=5, step=1)

# make tensor from line space
m = torch.linspace(start=0, end=1, steps=5)

# make tensor from log space
o = torch.logspace(start=0, end=1, steps=5)

# make identity matrix
p = torch.eye(n=3, m=3)

# matrix whose elements are all same values
q = torch.full(size=(3, 3), fill_value=7)

# generates 2 random numbers, normal(0, 1)
r = torch.randn(2)

# generates 2x2 matrix of random numbers, normal(0, 1)
s = torch.randn(2, 2)

# generates 2 random numbers, uniform [0, 1]
t = torch.rand(2)

# generates 2x2 random numbers, uniform [0, 1]
u = torch.rand(2, 2)

print('a: ', a)
print('b: ', b)
print('c: ', c)
print('d: ', d)
print('e: ', e)
print('f: ', f)
print('g: ', g)
print('h: ', h)
print('i: ', i)
print('j: ', j)
print('k: ', k)
print('l: ', l)
print('m: ', m)
print('o: ', o)
print('p: ', p)
print('q: ', q)
print('r: ', r)
print('s: ', s)
print('t: ', t)
print('u: ', u)

a:  tensor([1])
b:  tensor([1, 2])
c:  tensor([1., 2.])
d:  tensor([[1., 2.],
        [3., 4.]])
e:  tensor([1., 2., 3.])
f:  tensor([1., 2.], dtype=torch.float64)
g:  tensor([0.])
h:  tensor([[0., 0.]])
i:  tensor([[0., 0.],
        [0., 0.]])
j:  tensor([[-4.3562e-38,  4.5768e-41],
        [ 2.8082e+17,  3.0908e-41]])
k:  tensor([[1., 1.],
        [1., 1.]])
l:  tensor([0, 1, 2, 3, 4])
m:  tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])
o:  tensor([ 1.0000,  1.7783,  3.1623,  5.6234, 10.0000])
p:  tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
q:  tensor([[7., 7., 7.],
        [7., 7., 7.],
        [7., 7., 7.]])
r:  tensor([-0.0482, -0.1413])
s:  tensor([[ 0.1003,  0.3367],
        [-0.1006, -0.2017]])
t:  tensor([0.1767, 0.4287])
u:  tensor([[0.1576, 0.3804],
        [0.6288, 0.3828]])


## Indexing, slicing, joining and mutating

### Concatenating

In [50]:
a = torch.tensor([1., 2.])
b = torch.tensor([2., 3.])
torch.cat((a, b))

tensor([1., 2., 2., 3.])

### Index selecting

In [55]:
a = torch.tensor([[1, 2], [3, 4]])
i = torch.tensor([1])
torch.index_select(a, dim=1, index=i)

tensor([[2],
        [4]])

### Reshaping

Some data come as a single array, but you may reshape it into a tensor with different dimensions. 

In [56]:
a = torch.rand(784)
b = a.view(1, 28, 28)
c = a.reshape(1, 28, 28)

print(a.shape)
print(b.shape)
print(c.shape)

torch.Size([784])
torch.Size([1, 28, 28])
torch.Size([1, 28, 28])


### Permuting

Some data come in `HWC` (height, width, channel) format, but PyTorch needs `CHW` format. Here's how to `permute` the data.

In [57]:
hwc = torch.rand(640, 480, 3)
chw = hwc.permute(2, 0, 1)

print(hwc.shape)
print(chw.shape)

torch.Size([640, 480, 3])
torch.Size([3, 640, 480])


### Squeezing

Get rid of all the dimensions with `size 1`.

In [60]:
# a 2x1x2x1x2 tensor
a = torch.zeros(2, 1, 2, 1, 2)
b = torch.squeeze(a)

print('a: ', a.shape)
print('b: ', b.shape)

a:  torch.Size([2, 1, 2, 1, 2])
b:  torch.Size([2, 2, 2])


### Stacking

In [66]:
a = torch.zeros(1, 2)
b = torch.zeros(1, 2)
c = torch.stack([a, b], dim=0)
d = torch.stack([a, b], dim=1)

print('c: ', c.shape, ': ', c)
print('d: ', d.shape, ': ', d)

c:  torch.Size([2, 1, 2]) :  tensor([[[0., 0.]],

        [[0., 0.]]])
d:  torch.Size([1, 2, 2]) :  tensor([[[0., 0.],
         [0., 0.]]])


In [68]:
a = torch.zeros(2, 3)
b = torch.t(a)

print('a: ', a.shape)
print('b: ', b.shape)

a:  torch.Size([2, 3])
b:  torch.Size([3, 2])


### Type conversion

In [58]:
# torch.LongTensor
a = torch.tensor([[0, 1], [2, 3]])

# torch.FloatTensor
b = a.to(dtype=torch.float32)
b.type()

'torch.FloatTensor'

### Unbinding

In [69]:
a = torch.rand(3, 3)
b = torch.unbind(a)
b

(tensor([0.5438, 0.4313, 0.5042]),
 tensor([0.8776, 0.5433, 0.4637]),
 tensor([0.2229, 0.4790, 0.8437]))

### Unsqueeze

In [73]:
a = torch.tensor([1, 2, 3])
b = torch.unsqueeze(a, 0)
c = torch.unsqueeze(a, 1)

print('a: ', a.shape)
print('b: ', b.shape)
print('c: ', c.shape)

a:  torch.Size([3])
b:  torch.Size([1, 3])
c:  torch.Size([3, 1])


### Where

In [75]:
a = torch.randn(3, 3)
b = torch.ones(3, 3)
torch.where(a > 0, a, b)

tensor([[0.4666, 1.0000, 0.8935],
        [1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000]])

## Random sampling

## Math operations

In [1]:
a = torch.tensor([1., 2.])
b = torch.tensor([2., 3.])

c = a + b
d = a - b
e = a * b
f = a / b
g = a.dot(b)

print(c)
print(d)
print(e)
print(f)
print(g)

tensor([3., 5.])
tensor([-1., -1.])
tensor([2., 6.])
tensor([0.5000, 0.6667])
tensor(8.)


In [2]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[1, 2], [3, 4]])

c = a + b
d = a - b
e = a * b
f = a / b

print(c)
print(d)
print(e)
print(f)
print(g)

tensor([[2, 4],
        [6, 8]])
tensor([[0, 0],
        [0, 0]])
tensor([[ 1,  4],
        [ 9, 16]])
tensor([[1, 1],
        [1, 1]])
tensor(8.)


## Getting min and max values

In [7]:
a = torch.rand(10)
a.min().item()

0.1018722653388977

In [8]:
a = torch.rand(10)
a.max().item()

0.984703004360199

## Device-agnostic code

In [12]:
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
print(f'device = {device}')

a = torch.tensor(10, device=device)
b = torch.rand(2, device=device)

print(a)
print(b)

device = cuda
tensor(10, device='cuda:0')
tensor([0.8639, 0.6796], device='cuda:0')
