# Tensor

## Basic operations

In [31]:
import torch

a = torch.tensor([1., 2.])
b = torch.tensor([2., 3.])

c = a + b
d = a - b
e = a * b
f = a / b

print(c, d, e, f)
a.dot(b)
a.T

tensor([3., 5.]) tensor([-1., -1.]) tensor([2., 6.]) tensor([0.5000, 0.6667])


tensor([1., 2.])

In [27]:
a = torch.empty(1).new_full([3, 2], fill_value=0.3)
b = torch.empty(1).new_full([3, 2], fill_value=0.5)

c = a + b
d = a - b
e = a * b
f = a / b

print(c)
print(d)
print(e)
print(f)

tensor([[0.8000, 0.8000],
        [0.8000, 0.8000],
        [0.8000, 0.8000]])
tensor([[-0.2000, -0.2000],
        [-0.2000, -0.2000],
        [-0.2000, -0.2000]])
tensor([[0.1500, 0.1500],
        [0.1500, 0.1500],
        [0.1500, 0.1500]])
tensor([[0.6000, 0.6000],
        [0.6000, 0.6000],
        [0.6000, 0.6000]])


## Random number, normal distribution, m=0, v=1

In [9]:
torch.randn(2)

tensor([ 0.1578, -0.9685])

## Random number, uniform distribution [0, 1]

In [11]:
torch.rand(2)

tensor([0.3872, 0.0746])

## Timing events

In [15]:
start_event = torch.cuda.Event(enable_timing=True)
end_event = torch.cuda.Event(enable_timing=True)
start_event.record()

torch.tensor([1.0 for _ in range(1000000)])

end_event.record()
torch.cuda.synchronize()  # Wait for the events to be recorded!
elapsed_time_ms = start_event.elapsed_time(end_event)
elapsed_time_ms

56.42854309082031

## Device-agnostic code

In [18]:
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
print(device)

cuda


In [19]:
torch.empty(2)

tensor([1.6115e-43, 4.4842e-44])