# Tensor

## Basic operations

In [1]:
import torch

a = torch.tensor([1., 2.])
b = torch.tensor([2., 3.])

c = a + b
d = a - b
e = a * b
f = a / b
g = a.dot(b)

print(c)
print(d)
print(e)
print(f)
print(g)

tensor([3., 5.])
tensor([-1., -1.])
tensor([2., 6.])
tensor([0.5000, 0.6667])
tensor(8.)


In [2]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[1, 2], [3, 4]])

c = a + b
d = a - b
e = a * b
f = a / b

print(c)
print(d)
print(e)
print(f)
print(g)

tensor([[2, 4],
        [6, 8]])
tensor([[0, 0],
        [0, 0]])
tensor([[ 1,  4],
        [ 9, 16]])
tensor([[1, 1],
        [1, 1]])
tensor(8.)


## Random number, normal distribution, m=0, v=1

In [3]:
torch.randn(2)

tensor([-0.0370,  0.2643])

In [4]:
torch.randn(2, 2)

tensor([[ 0.4181,  0.2541],
        [-0.5062,  1.6779]])

## Random number, uniform distribution [0, 1]

In [5]:
torch.rand(2)

tensor([0.9491, 0.7387])

In [6]:
torch.rand(2, 2)

tensor([[0.8930, 0.4646],
        [0.3898, 0.3706]])

## Getting min and max values

In [7]:
a = torch.rand(10)
a.min().item()

0.1018722653388977

In [8]:
a = torch.rand(10)
a.max().item()

0.984703004360199

## Converting to type

In [9]:
# torch.LongTensor
a = torch.tensor([[0, 1], [2, 3]])

# torch.FloatTensor
b = a.to(dtype=torch.float32)
b.type()

'torch.FloatTensor'

## Reshaping

In [10]:
a = torch.rand(784)
b = a.view(1, 28, 28)
c = a.reshape(1, 28, 28)

print(a.shape)
print(b.shape)
print(c.shape)

torch.Size([784])
torch.Size([1, 28, 28])
torch.Size([1, 28, 28])


## Permuting

In [11]:
hwc = torch.rand(640, 480, 3)
chw = hwc.permute(2, 0, 1)

print(hwc.shape)
print(chw.shape)

torch.Size([640, 480, 3])
torch.Size([3, 640, 480])


## Device-agnostic code

In [12]:
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
print(f'device = {device}')

a = torch.tensor(10, device=device)
b = torch.rand(2, device=device)

print(a)
print(b)

device = cuda
tensor(10, device='cuda:0')
tensor([0.8639, 0.6796], device='cuda:0')
